# -*- makefile -*-
#----------------------------------------------------------------------------
#       GNU ACE Workspace
#
# $Id: GNUACEWorkspaceCreator.pm 77499 2007-03-02 18:19:05Z elliott_c $
#
# This file was generated by MPC.  Any changes made directly to
# this file will be lost the next time it is generated.
#
# MPC Command:
# /home/schmidt/adaptive/DOC_ROOT/ACE/bin/mwc.pl -type gnuace
#
#----------------------------------------------------------------------------

MAKEFILE = GNUmakefile

ifeq ($(findstring k,$(MAKEFLAGS)),k)
  KEEP_GOING = -
endif

include $(ACE_ROOT)/include/makeinclude/macros.GNU

all: Quoter_Simple_Client Quoter_Simple_Impl_Repo_Client Quoter_Simple_Impl_Repo_Server Quoter_Simple_ImprovedServer Quoter_Simple_Persistent_Client Quoter_Simple_Persistent_Server Quoter_Simple_Server

REMAINING_TARGETS := $(subst all, , $(TARGETS_NESTED:.nested=)) $(CUSTOM_TARGETS)

$(REMAINING_TARGETS):
	@cd Client && $(MAKE) -f GNUmakefile.Quoter_Simple_Client $(@)
	@cd Impl-Repo && $(MAKE) -f GNUmakefile.Quoter_Simple_Impl_Repo_Client $(@)
	@cd Impl-Repo && $(MAKE) -f GNUmakefile.Quoter_Simple_Impl_Repo_Server $(@)
	@cd ImprovedServer && $(MAKE) -f GNUmakefile.Quoter_Simple_ImprovedServer $(@)
	@cd Persistent && $(MAKE) -f GNUmakefile.Quoter_Simple_Persistent_Client $(@)
	@cd Persistent && $(MAKE) -f GNUmakefile.Quoter_Simple_Persistent_Server $(@)
	@cd Server && $(MAKE) -f GNUmakefile.Quoter_Simple_Server $(@)

.PHONY: Quoter_Simple_Client
Quoter_Simple_Client:
	@cd Client && $(MAKE) -f GNUmakefile.Quoter_Simple_Client all

.PHONY: Quoter_Simple_Impl_Repo_Client
Quoter_Simple_Impl_Repo_Client:
	@cd Impl-Repo && $(MAKE) -f GNUmakefile.Quoter_Simple_Impl_Repo_Client all

.PHONY: Quoter_Simple_Impl_Repo_Server
Quoter_Simple_Impl_Repo_Server:
	@cd Impl-Repo && $(MAKE) -f GNUmakefile.Quoter_Simple_Impl_Repo_Server all

.PHONY: Quoter_Simple_ImprovedServer
Quoter_Simple_ImprovedServer:
	@cd ImprovedServer && $(MAKE) -f GNUmakefile.Quoter_Simple_ImprovedServer all

.PHONY: Quoter_Simple_Persistent_Client
Quoter_Simple_Persistent_Client:
	@cd Persistent && $(MAKE) -f GNUmakefile.Quoter_Simple_Persistent_Client all

.PHONY: Quoter_Simple_Persistent_Server
Quoter_Simple_Persistent_Server:
	@cd Persistent && $(MAKE) -f GNUmakefile.Quoter_Simple_Persistent_Server all

.PHONY: Quoter_Simple_Server
Quoter_Simple_Server:
	@cd Server && $(MAKE) -f GNUmakefile.Quoter_Simple_Server all

project_name_list:
	@echo Quoter_Simple_Client
	@echo Quoter_Simple_Impl_Repo_Client
	@echo Quoter_Simple_Impl_Repo_Server
	@echo Quoter_Simple_ImprovedServer
	@echo Quoter_Simple_Persistent_Client
	@echo Quoter_Simple_Persistent_Server
	@echo Quoter_Simple_Server
